servers:
  - dev.bar.com
  - foo.bar.com

---

spring:
  config:
    activate:
      on-profile: local

kdt:
  version: "v1.0"
  minimum-order-amount: 1
  support-vendors:
    - a
    - b
    - c
    - d
  description: |- # - 기호가 있으면 줄바꿈 포함하지 않음
    line 1 hello world
    line 2 xxxx
    line 3

---

spring:
  config:
    activate:
      on-profile: dev

kdt:
  version: "v1.0"
  minimum-order-amount: 1
  support-vendors:
    - dev - a
    - dev - b
  description: |- # - 기호가 있으면 줄바꿈 포함하지 않음
    line 1 dev
    line 2 dev
    line 3 dev

---